import type { Metadata } from "next";
import localFont from "next/font/local";
import ClientOnlyProvider from '@/components/ClientOnlyProvider'; // Import the client-side wrapper

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the children in the client-side ApolloProvider */}
        <ClientOnlyProvider>
          {children}
        </ClientOnlyProvider>
      </body>
    </html>
  );
}
